/* inline every src module into a single self-contained page */
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

const SRC = 'src';

/* ---- content ------------------------------------------------------------
   Authored copy lives in content/*.json but is INLINED here, not fetched at
   runtime: the published artifact runs under a CSP that blocks external
   requests, and fetch() on a file:// page is blocked by CORS, so a runtime
   load would leave the screen blank exactly where it matters most. Generating
   a module into src/ means the dev page picks it up too, with no second path. */

// mirrors the glyph table in src/10_font.js — anything else draws as a gap
const FONT_CHARS = /^[A-Z0-9 .,:;!?$+\-/\\%#()[\]*=<>'"_&@^~]*$/;

// the virtual screen, and the scale each field is drawn at in overlayWinners
const VW = 384, EDGE = 8;
const FIELD_SCALE = { slogan: 2, attribution: 1, credit: 1 };
const textPx = (s, k) => (s.length ? s.length * 6 - 1 : 0) * k;

function buildContent() {
  const raw = JSON.parse(readFileSync(join('content', 'winners.json'), 'utf8'));
  const out = {};
  for (const [k, v] of Object.entries(raw)) {
    if (k.startsWith('_')) continue;                       // notes to the author
    const list = Array.isArray(v) ? v : [v];
    const scale = FIELD_SCALE[k] || 1;
    for (const s of list) {
      if (typeof s !== 'string') throw new Error(`content/winners.json: "${k}" must be a string or array of strings`);
      const up = s.toUpperCase();
      if (!FONT_CHARS.test(up)) {
        const bad = [...new Set([...up].filter((ch) => !FONT_CHARS.test(ch)))].join(' ');
        throw new Error(`content/winners.json: "${k}" uses characters the 5x7 font cannot draw: ${bad}`);
      }
      // Width matters as much as charset: the copy is centred on a 384px
      // screen, so an over-long line silently runs off BOTH edges. The note in
      // the JSON said so, but a note is not a guard.
      const w = textPx(up, scale);
      if (w > VW - EDGE) {
        const max = Math.floor((VW - EDGE) / scale / 6);
        throw new Error(
          `content/winners.json: "${k}" is ${w}px wide at scale ${scale}, but the screen is ${VW}px.\n` +
          `  ${JSON.stringify(s)} is ${s.length} characters; the limit at this scale is ${max}.\n` +
          `  Trim ${s.length - max} character${s.length - max === 1 ? '' : 's'}, or split it across the array.`);
      }
    }
    out[k] = v;
  }
  for (const need of ['slogan', 'attribution', 'credit']) {
    if (!(need in out)) throw new Error(`content/winners.json is missing "${need}"`);
  }
  writeFileSync(join(SRC, '05_content.js'),
    '/* GENERATED by build.mjs from content/winners.json — do not edit by hand. */\n' +
    "'use strict';\n\nconst CONTENT = " + JSON.stringify(out, null, 2) + ';\n');
  return out;
}

const content = buildContent();

const files = readdirSync(SRC).filter((f) => f.endsWith('.js')).sort();
const code = files.map((f) => `\n/* ===== ${f} ===== */\n` + readFileSync(join(SRC, f), 'utf8')).join('\n');

const shell = readFileSync('shell.html', 'utf8');
if (!shell.includes('/*__GAME__*/')) throw new Error('shell.html is missing the /*__GAME__*/ marker');

const out = shell.replace('/*__GAME__*/', () => code);
writeFileSync('taco-shop.html', out);

// dev page: same shell, but load the modules from disk so edits are instant
const dev = shell.replace(
  /<script>[\s\S]*?<\/script>/,
  files.map((f) => `<script src="${SRC}/${f}"></script>`).join('\n')
);
writeFileSync('index.html', '<!doctype html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n<meta name="viewport" content="width=device-width,initial-scale=1">\n' +
  dev.slice(0, dev.indexOf('</style>') + 8) + '\n</head>\n<body>\n' +
  dev.slice(dev.indexOf('</style>') + 8) + '\n</body>\n</html>\n');

console.log(`built taco-shop.html  (${(out.length / 1024).toFixed(1)} kB, ${files.length} modules)`);
console.log(`  content: "${String(content.slogan).slice(0, 40)}"`);
