/* GENERATED by build.mjs from content/*.json — do not edit by hand. */
'use strict';

const CONTENT = {
  "slogan": [
    "\"WINNERS DON'T USE DRUGS.",
    "THEY DRINK.\""
  ],
  "attribution": [
    "KASH S. PATEL , DIRECTOR, FBI"
  ],
  "credit": "CREDIT: 0"
};

const HAYS = {
  "streetsNS": [
    "ELM ST",
    "WALNUT ST",
    "ASH ST",
    "FORT ST",
    "MAIN ST",
    "OAK ST",
    "PINE ST",
    "ALLEN ST",
    "MILNER ST"
  ],
  "streetsEW": [
    "12TH ST",
    "11TH ST",
    "10TH ST",
    "9TH ST",
    "8TH ST",
    "7TH ST",
    "6TH ST",
    "5TH ST",
    "4TH ST"
  ],
  "shop": {
    "bx": 1,
    "by": 3
  },
  "zoning": [
    [
      "res",
      "res",
      "church",
      "retail",
      "retail",
      "com",
      "res",
      "res"
    ],
    [
      "res",
      "res",
      "com",
      "retail",
      "retail",
      "res",
      "res",
      "res"
    ],
    [
      "rail",
      "rail",
      "rail",
      "rail",
      "rail",
      "rail",
      "rail",
      "rail"
    ],
    [
      "apts",
      "shop",
      "com",
      "retail",
      "retail",
      "auto",
      "res",
      "auto"
    ],
    [
      "res",
      "church",
      "res",
      "civic",
      "civic",
      "com",
      "com",
      "auto"
    ],
    [
      "apts",
      "res",
      "res",
      "civic",
      "apts",
      "res",
      "res",
      "church"
    ],
    [
      "res",
      "res",
      "res",
      "res",
      "res",
      "res",
      "res",
      "res"
    ],
    [
      "res",
      "res",
      "res",
      "res",
      "park",
      "res",
      "park",
      "res"
    ]
  ]
};
