/* GENERATED by build.mjs from content/*.json — do not edit by hand. */
'use strict';

const CONTENT = {
  "slogan": [
    "\"WINNERS DON'T USE DRUGS.",
    "THEY DRINK.\""
  ],
  "attribution": [
    "KASH S. PATEL , DIRECTOR, FBI"
  ],
  "credit": "CREDIT: 0"
};

const HAYS = {
  "streetsNS": [
    "ELM ST",
    "WALNUT ST",
    "ASH ST",
    "FORT ST",
    "MAIN ST",
    "OAK ST",
    "PINE ST",
    "ALLEN ST",
    "MILNER ST"
  ],
  "streetsEW": [
    "12TH ST",
    "11TH ST",
    "10TH ST",
    "9TH ST",
    "8TH ST",
    "7TH ST",
    "6TH ST",
    "5TH ST",
    "4TH ST"
  ],
  "shop": {
    "bx": 1,
    "by": 3
  },
  "zoning": [
    [
      "res",
      "res",
      "church",
      "retail",
      "retail",
      "com",
      "res",
      "res"
    ],
    [
      "res",
      "res",
      "com",
      "retail",
      "retail",
      "res",
      "res",
      "res"
    ],
    [
      "rail",
      "rail",
      "rail",
      "rail",
      "rail",
      "rail",
      "rail",
      "rail"
    ],
    [
      "apts",
      "shop",
      "com",
      "retail",
      "retail",
      "auto",
      "res",
      "auto"
    ],
    [
      "res",
      "church",
      "res",
      "civic",
      "civic",
      "com",
      "com",
      "auto"
    ],
    [
      "apts",
      "res",
      "res",
      "civic",
      "apts",
      "res",
      "res",
      "church"
    ],
    [
      "res",
      "res",
      "res",
      "res",
      "res",
      "res",
      "res",
      "res"
    ],
    [
      "res",
      "res",
      "res",
      "res",
      "park",
      "res",
      "park",
      "res"
    ]
  ]
};

const ATTRACT = {
  "title": {
    "seconds": 30,
    "wordmarkHold": 3
  },
  "winners": {
    "seconds": 15
  },
  "scores": {
    "seconds": 15
  },
  "demo": {
    "seconds": 90
  }
};

const SCORES = {
  "board": [
    {
      "ini": "MJS",
      "cents": 9600
    },
    {
      "ini": "JAX",
      "cents": 7250
    },
    {
      "ini": "RED",
      "cents": 5840
    },
    {
      "ini": "TAC",
      "cents": 4610
    },
    {
      "ini": "UPX",
      "cents": 3990
    },
    {
      "ini": "HAY",
      "cents": 3120
    },
    {
      "ini": "ELM",
      "cents": 2450
    },
    {
      "ini": "FRT",
      "cents": 1880
    },
    {
      "ini": "BOB",
      "cents": 1240
    },
    {
      "ini": "KAS",
      "cents": 640
    }
  ]
};
