/* GENERATED by build.mjs from content/winners.json — do not edit by hand. */
'use strict';

const CONTENT = {
  "slogan": "\"WINNERS DON'T USE DRUGS\"",
  "attribution": [
    "WILLIAM S. SESSIONS , DIRECTOR, FBI"
  ],
  "credit": "CREDIT: 0"
};
